### ISSUE TITLE
run "lstm_data_generation.m" error

### ISSUE THREAD

**Issue by virteki** [vincentbecker/TouchSense#1]
when I run lstm_data_generation.m file , I got a pop window. And I choose the "data_preprocessing/data" folder , but some error happened.

References to fields that do not exist "folder"
error: lstm_data_generation (line 18)
    if (~isempty(dir(strcat(sub_folders(k).folder, filesep, sub_folders(k).name, filesep, '*.csv'))))

**Comment by vincentbecker** [comment]
Thanks for pointing out the issue. This is a problem concerning older versions of MATLAB. We fixed it, it should work now.
